# Maintainer: Ryan Kes <ryan@andthensome.nl>
#
# Stable channel: builds from a tagged release tarball. `pkgname=example` is
# a placeholder — this PKGBUILD packages this template repository's own
# trivial demo (example.sh + Makefile) so CI has something real to build and
# lint on every push, instead of a PKGBUILD nothing ever exercises. Adapting
# this template for a real project means replacing pkgname, pkgdesc, url,
# source, depends/makedepends and build()/package() with that project's own
# — the two-channel layout, CI, and .SRCINFO handling all stay as they are.
#
# `pkgver`'s trailing comment is release-please's generic extra-files
# marker (see release-please-config.json): every release-please release
# bumps the number here to match the tag it just cut. .SRCINFO does NOT
# get regenerated by that bump — see README.md's "Two release channels"
# section for why that's deliberate and what to run afterwards.

pkgname=example
pkgver=0.1.0 # x-release-please-version
pkgrel=1
pkgdesc="Demo package built from the scaffold-arch-package template"
arch=('x86_64' 'aarch64')
url="https://github.com/alrayyes/scaffold-arch-package"
license=('LicenseRef-custom')
depends=('bash')
makedepends=('make')
source=("$pkgname-$pkgver.tar.gz::https://github.com/alrayyes/scaffold-arch-package/archive/refs/tags/v$pkgver.tar.gz")
# SKIP until the first tag exists to compute a real checksum against — see
# README.md's "Publishing to the AUR" section. The AUR rejects SKIP on a
# non-VCS source, so this has to become a real sha256sum (`updpkgsums`)
# before this ever gets pushed there.
sha256sums=('SKIP')

build() {
  cd "scaffold-arch-package-$pkgver"
  make build
}

package() {
  cd "scaffold-arch-package-$pkgver"
  make DESTDIR="$pkgdir" PREFIX=/usr install
}
